version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "18:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 10
    reviewers:
      - "fkrzski"
    labels:
      - "dependencies"